# Generated by Django 3.2.1 on 2021-06-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0002_rename_models_mdels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mdels',
            new_name='models',
        ),
    ]
