# Generated by Django 3.2.1 on 2021-06-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0003_rename_mdels_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='txt',
            field=models.CharField(max_length=50),
        ),
    ]
