# Generated by Django 3.2.1 on 2021-06-05 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kuki', '0004_alter_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='cd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='models',
            name='txt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
