# Generated by Django 2.2.14 on 2021-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0008_auto_20210615_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='intrest',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
