# Generated by Django 2.2.14 on 2021-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0012_auto_20210617_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
