# Generated by Django 2.2.14 on 2021-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0013_auto_20210617_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
