# Generated by Django 2.2.14 on 2021-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0014_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='bio',
            field=models.TextField(default='no bio...'),
        ),
    ]
