# Generated by Django 2.2.14 on 2021-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0015_report_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hai',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
