# Generated by Django 2.2.14 on 2021-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0016_profile_hai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hai',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
