# Generated by Django 2.2.14 on 2021-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0017_auto_20210617_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
