# Generated by Django 2.2.14 on 2021-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuki', '0019_auto_20210618_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/klc.jpg', upload_to='avatars'),
        ),
    ]
